# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Journey as Cloud networking engineer
email: imrit96singh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Started My technical journey as an electrical engineer in India 
  and came to Canada to upgrade My technical skills. A strong headed person
  on the lookout for technical problem solving by utilising the Network, 
  Telecommunications and Cloud based knowledge.
  Having faced a lack of support and No guidance from an experienced Senior
  in a new environment I decided to help all My juniors by becoming a peer 
  mentor, peer tutor, and a volunteer in My college. 
  After My graduation I have intended to keep helping new students via My blogs
  where I will share all the problems be they technical or non-technical I faced
  during My time at College.
  With time I intend to make this site more interactive and help everyone with
  the knowledge I have gained!
  Let us begin the Journey! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imrit96.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: coming-soon
github_username:  imrit96

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
